<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function mailchimp_subscribe_theme() {
  return [
    'subscribe_form_block' => [
      'template' => 'subscribe-form-block',
      'variables' => [
      ],
    ],
  ];
}

/**
 * Implements hook_form_alter().
 */
function mailchimp_subscribe_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'webform_submission_subscribe_add_form' ||
    str_contains($form_id, 'webform_submission_subscribe_')) {
    $form['actions']['submit']['#submit'][] = '_subscribe_after_submit';
    $form['#attached']['library'][] = 'mailchimp_subscribe/mailchimp_subscribe';
  }
}

/**
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 */
function _subscribe_after_submit(array $form, FormStateInterface $form_state) {
  $email = $form_state->getValue('e_mail');
  if ($email != '') {

    $visible_tags = $form_state->getValue('tags') ?? [];
    $hidden_tags = explode(',', $form_state->getValue('hidden_tags'));
    $double_optin = $form_state->getValue('double_optin') ?? TRUE;
    $first_name = $form_state->getValue('first_name') ?? '';
    $last_name = $form_state->getValue('last_name') ?? '';

    $tags = array_merge($visible_tags, $hidden_tags);

    $merge_fields =         [
      'FNAME' => $first_name,
      'LNAME' => $last_name,
    ];

    /** @var \Drupal\mailchimp_subscribe\Service\Mailchimp $mailchimp */
    $mailchimp = \Drupal::service('mailchimp');
    if ($result = $mailchimp->subscribe(
      $email,
      \Drupal::languageManager()->getCurrentLanguage()->getId(),
      $merge_fields,
      $tags,
      [],
      $double_optin,
    )) {
      $mailchimp->updateTags($email, $tags);
      switch ($result) {
        // Not yet existing.
        case 'pending';
          if ($double_optin) {
            \Drupal::messenger()
              ->addMessage(t('Your subscription to the newsletter has been successfully received. You will receive another email to confirm.'));
          }
          else {
            \Drupal::messenger()
              ->addMessage(t('Your subscription to the newsletter has been successfully received.'));
          }
          break;
        // Existing and confirmed earlier.
        case 'subscribed':
          \Drupal::messenger()
            ->addMessage(t('Your subscription to the newsletter has been successfully received.'));
          break;

        default:
          \Drupal::messenger()
            ->addError(t('Something went wrong while subscribing. Please try again later.'));
      }
    }
    else {
      \Drupal::messenger()
        ->addError(t('Something went wrong while subscribing. Please try again later.'));
    }
  }
}
